In [111]:
import numpy as np
import scipy
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder,MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split,StratifiedShuffleSplit,cross_val_score,GridSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,f1_score,recall_score, classification_report
from sklearn.feature_selection import VarianceThreshold
from xgboost import XGBClassifier
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout,TimeDistributed,Bidirectional
from keras.utils.np_utils import to_categorical
from keras.regularizers import l2
import matplotlib.pyplot as plt
import seaborn as sns

In [185]:
df1 = pd.read_csv('D:/我的文档/手机大数据/数据/sf训练集（扩充）230202-1.csv',header=None)
df2 = pd.read_csv('D:/我的文档/手机大数据/数据/sf训练集（扩充）230202-2.csv',header=None)
df3 = pd.read_csv('D:/我的文档/手机大数据/数据/sf测试集（扩充）230202.csv',header=None)
# df1 = pd.read_csv('D:/我的文档/手机大数据/数据/sfdata1.csv',header=None)
# df3 = pd.read_csv('D:/我的文档/手机大数据/数据/sfdata2.csv',header=None)
# df2 = pd.read_csv('D:/我的文档/手机大数据/数据/sfdata3.csv',header=None,encoding='gbk')

In [186]:
df2.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,020f674a3f6de9b06dd95e6e384d2b56a6c5265e,2021/7/11 16:39,1,1,0,0,0,0,0,4.0,2.483306,37.249584,0.000000,1.000000,2
1,020f674a3f6de9b06dd95e6e384d2b56a6c5265e,2021/7/11 16:43,1,0,0,0,0,0,0,4.0,2.483306,37.249584,0.000000,-0.972970,2
2,020f674a3f6de9b06dd95e6e384d2b56a6c5265e,2021/7/11 16:56,1,1,0,0,0,0,0,13.0,5.373474,24.800649,-0.957610,-0.996788,2
3,020f674a3f6de9b06dd95e6e384d2b56a6c5265e,2021/7/11 17:04,1,1,0,0,0,0,0,8.0,2.403277,18.024580,-0.847009,-0.998361,2
4,020f674a3f6de9b06dd95e6e384d2b56a6c5265e,2021/7/11 17:15,1,1,0,0,0,0,0,11.0,3.526302,19.234372,0.109981,-0.999691,2

In [187]:
df1[0].value_counts()

245                                         66
215                                         65
28ca868a1bd9e5dc77d20492e5bbf29a18fd3204    63
255                                         61
224                                         59
                                            ..
238                                          4
0335ec4ba67adc3aea7f3da8e01e66a86d57d8e3     4
198                                          4
408                                          4
425                                          1
Name: 0, Length: 432, dtype: int64

In [188]:
y1 = df1[14]
y2 = df2[14]
y3 = df3[14]
# y1 = df1[23]
# y2 = df2[23]
# y3 = df3[23]

In [189]:
x1 = df1[[0,2,3,4,5,6,7,8,9,10,11,12,13]]
x2 = df2[[0,2,3,4,5,6,7,8,9,10,11,12,13]]
x3 = df3[[0,2,3,4,5,6,7,8,9,10,11,12,13]]
# x1 = df1[[0,11,12,13,14,15,16,17,18,19,20,21,22]]
# x2 = df2[[0,11,12,13,14,15,16,17,18,19,20,21,22]]
# x3 = df3[[0,11,12,13,14,15,16,17,18,19,20,21,22]]

In [190]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size = 0.2)

In [191]:
x1_0 = x1.drop([0],axis = 1)
x1_0_train = x1_train.drop([0],axis = 1)#df1中的训练集
x1_0_test = x1_test.drop([0],axis = 1)#df1中的测试集
x2_0_test = x2.drop([0],axis = 1)
x3_0_test = x3.drop([0],axis = 1)
x3_0_test

,2,3,4,5,6,7,8,9,10,11,12,13
0,0,1,0,0,0,0,0,10.000000,6.362537,38.175225,0.000000,1.000000
1,0,1,0,0,0,0,0,10.000000,6.362537,38.175225,0.000000,-0.865950
2,0,1,1,1,0,0,0,10.000000,4.896649,29.379891,-0.879533,-0.624838
3,0,1,0,1,0,0,0,21.000000,12.806665,36.590473,0.343361,-0.958911
4,0,1,0,0,0,0,0,9.000000,2.675966,17.839774,-2.083411,-0.111902
...,...,...,...,...,...,...,...,...,...,...,...,...
5838,0,0,0,1,0,0,0,87.200000,0.242256,0.166690,-0.009226,1.000000
5839,0,0,0,1,0,0,0,197.950000,0.000000,0.000000,-0.000842,1.000000
5840,0,0,0,1,0,0,0,11.533333,0.846207,4.402232,0.381696,0.999661
5841,0,0,0,1,0,0,0,24.550000,0.444122,1.085431,-0.135104,-0.998487
5842,0,0,0,1,0,0,0,3.866667,0.402393,6.244023,1.334118,-1.000000

In [192]:
# 数据预处理
def mean_std(X):
    # 计算每列的均值和标准差
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    return mean, std
# 对数据集进行标准化
x1_0_train_scaled = (x1_0_train - mean_std(x1_0_train)[0]) / mean_std(x1_0_train)[1]
x1_0_test_scaled = (x1_0_test - mean_std(x1_0_test)[0]) / mean_std(x1_0_test)[1]
x3_0_test_scaled = (x3_0_test - mean_std(x3_0_test)[0]) / mean_std(x3_0_test)[1]

In [193]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans

In [194]:
# 使用k-means算法将数据分成k个群集
def kmeans_model():
    kmeans = KMeans(n_clusters=5)
    kmeans.fit(x3_0_test_scaled)
    #f1_x3 = f1_score(y3, kmeans.labels_,average='weighted')
    report = classification_report(y3, kmeans.labels_, labels=range(5), output_dict=True)
    f1_class = []
    for i in [0,1,2,3,4,'weighted avg']:
        f1 = report[str(i)]['f1-score']
        f1_class.append(f1)
    row_str = ','.join(str(num) for num in f1_class)
    return row_str

In [155]:
# kmeans_res = kmeans_model()
# print(kmeans_res)

In [156]:
# knn
def knn_model():
    x1_train1, x1_test1, y1_train1, y1_test1 = train_test_split(x1, y1, test_size = 0.2)
    x1_0_train1 = x1_train1.drop([0],axis = 1)#df1中的训练集
    x1_0_test1 = x1_test1.drop([0],axis = 1)#df1中的测试集
    x3_0_test1 = x3.drop([0],axis = 1)
    knn = KNeighborsClassifier(n_neighbors=3)
    # 拟合训练集
    knn.fit(x1_0_train1, y1_train1)
    # 预测测试集
    #y1_0_test_predict = knn.predict(x1_0_test)
    y3_0_test_predict = knn.predict(x3_0_test1)
    
    report = classification_report(y3, y3_0_test_predict, labels=range(5), output_dict=True)
    f1_class = []
    for i in [0,1,2,3,4,'weighted avg']:
        f1 = report[str(i)]['f1-score']
        f1_class.append(f1)
    row_str = ','.join(str(num) for num in f1_class)
    # 保存输出
    y3_mt = y3.values.reshape(y3.size,1)
    x3_mt = x3.values
    y3_0_test_predict_mt = y3_0_test_predict.reshape(y3_0_test_predict.size,1)
    output_mt = np.concatenate((x3_mt,y3_0_test_predict_mt,y3_mt),axis=1)
    output_df = pd.DataFrame(output_mt)
    output_df.to_csv('D:/我的文档/手机大数据/数据/识别结果-knn.csv', index=False, header=False)
    return row_str

In [157]:
knn_res = knn_model()
knn_res

'0.9534268863127924,0.7399859451862262,0.7488734125358459,0.7279151943462897,0.29067930489731436,0.793331487728207'

In [158]:
def rf_model():
    clf = RandomForestClassifier(max_depth=10, n_estimators=200,max_features=10)
    clf_model = clf.fit(x1_0_train, y1_train)
    y3_0_test_predict = clf_model.predict(x3_0_test)
#     f1_x3 = f1_score(y3, y3_0_test_predict,average='weighted')
    report = classification_report(y3, y3_0_test_predict, labels=range(5), output_dict=True)
    f1_class = []
    for i in [0,1,2,3,4,'weighted avg']:
        f1 = report[str(i)]['f1-score']
        f1_class.append(f1)
    row_str = ','.join(str(num) for num in f1_class)
        # 保存输出
    y3_mt = y3.values.reshape(y3.size,1)
    x3_mt = x3.values
    y3_0_test_predict_mt = y3_0_test_predict.reshape(y3_0_test_predict.size,1)
    output_mt = np.concatenate((x3_mt,y3_0_test_predict_mt,y3_mt),axis=1)
    output_df = pd.DataFrame(output_mt)
    output_df.to_csv('D:/我的文档/手机大数据/数据/识别结果-rf-2.csv', index=False, header=False)
    return row_str

In [159]:
rf_res = rf_model()
rf_res

'0.9694593479158068,0.9227843286420692,0.8603213844252162,0.8538812785388127,0.7995594713656387,0.9141677133810876'

In [160]:
def xgb_model():
    x1_train1, x1_test1, y1_train1, y1_test1 = train_test_split(x1, y1, test_size = 0.2)
    x1_0_train1 = x1_train1.drop([0],axis = 1)#df1中的训练集
    x1_0_test1 = x1_test1.drop([0],axis = 1)#df1中的测试集
    x3_0_test1 = x3.drop([0],axis = 1)
    # 训练模型
    model = XGBClassifier(n_estimators=200, max_depth=10, learning_rate=0.01,subsample=0.8,colsample_bytree=0.8, )
    model.fit(x1_0_train1, y1_train1)
    # 预测并评价
    y3_0_test_predict = model.predict(x3_0_test1)
    
    report = classification_report(y3, y3_0_test_predict, labels=range(5), output_dict=True)
    f1_class = []
    for i in [0,1,2,3,4,'weighted avg']:
        f1 = report[str(i)]['f1-score']
        f1_class.append(f1)
    row_str = ','.join(str(num) for num in f1_class)
        # 保存输出
    y3_mt = y3.values.reshape(y3.size,1)
    x3_mt = x3.values
    y3_0_test_predict_mt = y3_0_test_predict.reshape(y3_0_test_predict.size,1)
    output_mt = np.concatenate((x3_mt,y3_0_test_predict_mt,y3_mt),axis=1)
    output_df = pd.DataFrame(output_mt)
    output_df.to_csv('D:/我的文档/手机大数据/数据/识别结果-xgb.csv', index=False, header=False)
    return row_str

In [161]:
xgb_res = xgb_model()
xgb_res

'0.9680609932000824,0.9234285714285714,0.8613496932515337,0.8439955106621774,0.7798165137614678,0.9115826565361717'

In [129]:
def create_dataset(X, look_back):
    lenth = X.shape[1]-1
    mat = X[0,1:]
    fillmat = np.full([look_back - 1, lenth],0)
    dataX = np.vstack((fillmat,mat))
    premdn = X[0,0]
    i = 1
    count = 1
    while i < len(X):
        if (X[i][0] == premdn):
            if(count < look_back):
                temp = X[i-count:i+1, 1:]
                filltemp = fill_zeros(temp,look_back,lenth)
                dataX = np.vstack((dataX,filltemp))
            else:
                dataX = np.vstack((dataX, X[i-look_back+1:i + 1, 1:]))
            i += 1
            count += 1
        else:
            mat = X[i, 1:]
            fillmat = np.full([look_back - 1, lenth],0)
            fillmat = np.vstack((fillmat,mat))
            dataX = np.vstack((dataX,fillmat))
            premdn = X[i, 0]
            count = 1
            i += 1
    return np.array(dataX)
#填充初始值
def fill_zeros(mat,look_back,lenth):
    if mat.shape[0] < look_back:
        temp = np.full([look_back-mat.shape[0],lenth],0)
        temp = np.vstack((temp,mat))
        return temp
    else:
        return mat

In [162]:
def lstm_model():
    y1_5 = to_categorical(y1, num_classes=5).reshape(-1,5)
    y3_5 = to_categorical(y3, num_classes=5).reshape(-1,5)  

#     trainX = np.array(x1_0)
#     trainy = np.array(y1_5)
#     testy = np.array(y3_5)
#     testX = np.array(x3_0_test)
 
    look_back = 3
    trainX = create_dataset(np.array(x1_0),look_back)
    trainy = np.array(y1_5)
    testX = create_dataset(np.array(x3_0_test), look_back)
    testy = np.array(y3_5)
    
    train_n1 = int(trainX.shape[0]/look_back)
    test_n1 = int(testX.shape[0]/look_back)
    trainX = trainX.reshape((train_n1, look_back,trainX.shape[1])).astype('float32')
    testX = testX.reshape((test_n1, look_back,testX.shape[1])).astype('float32')
    trainy = trainy.reshape((train_n1, 5)).astype('float32')
    testy = testy.reshape((test_n1, 5)).astype('float32')
    
    model = Sequential()
    model.add(LSTM(32,input_shape=(trainX.shape[1],trainX.shape[2])))
    model.add(Dropout(0.4))
    model.add(Dense(5, activation='softmax'))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
    model.fit(trainX, trainy, epochs=50, batch_size=72, verbose=0)
    
    pred = model.predict(testX)
    yhat = np.argmax(pred, axis=1)
    y = np.argmax(testy, axis=1)
    
    report = classification_report(y, yhat, labels=range(5), output_dict=True)
    f1_class = []
    for i in [0,1,2,3,4,'weighted avg']:
        f1 = report[str(i)]['f1-score']
        f1_class.append(f1)
    row_str = ','.join(str(num) for num in f1_class)
    # 保存输出
    x3_mt = x3.values
    output_mt = np.concatenate((x3_mt,yhat.reshape(yhat.size,1),y.reshape(y.size,1)),axis = 1)
    output_df = pd.DataFrame(output_mt)
    output_df.to_csv('D:/我的文档/手机大数据/数据/识别结果-lstm.csv', index=False, header=False)
    return row_str

In [165]:
lstm_res = lstm_model()
lstm_res

'0.9660596026490066,0.9043137254901961,0.8474301902063941,0.864461045891142,0.8303571428571428,0.9093104830606445'

In [166]:
def bilstm_model():
    y1_5 = to_categorical(y1, num_classes=5).reshape(-1,5)
    y3_5 = to_categorical(y3, num_classes=5).reshape(-1,5)
    
#     trainX = np.array(x1_0)
#     trainy = np.array(y1_5)
#     testy = np.array(y3_5)
#     testX = np.array(x3_0_test)

    look_back = 3
    trainX = create_dataset(np.array(x1_0),look_back)
    trainy = np.array(y1_5)
    testX = create_dataset(np.array(x3_0_test), look_back)
    testy = np.array(y3_5)
    
    train_n1 = int(trainX.shape[0]/look_back)
    test_n1 = int(testX.shape[0]/look_back)
    trainX = trainX.reshape((train_n1, look_back,trainX.shape[1])).astype('float32')
    testX = testX.reshape((test_n1, look_back,testX.shape[1])).astype('float32')
    trainy = trainy.reshape((train_n1, 5)).astype('float32')
    testy = testy.reshape((test_n1, 5)).astype('float32')
    
    model = Sequential()
    model.add(Bidirectional(LSTM(32,input_shape=(trainX.shape[1],trainX.shape[2]))))
    model.add(Dropout(0.4))
    model.add(Dense(5, activation='softmax'))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
    model.fit(trainX, trainy, epochs=50, batch_size=72, verbose=0)
    
    pred = model.predict(testX)
    yhat = np.argmax(pred, axis=1)
    y = np.argmax(testy, axis=1)
    
    report = classification_report(y, yhat, labels=range(5), output_dict=True)
    f1_class = []
    for i in [0,1,2,3,4,'weighted avg']:
        f1 = report[str(i)]['f1-score']
        f1_class.append(f1)
    row_str = ','.join(str(num) for num in f1_class)
    # 保存输出
    x3_mt = x3.values
    output_mt = np.concatenate((x3_mt,yhat.reshape(yhat.size,1),y.reshape(y.size,1)),axis = 1)
    output_df = pd.DataFrame(output_mt)
    output_df.to_csv('D:/我的文档/手机大数据/数据/识别结果-bilstm.csv', index=False, header=False)
    return row_str

In [170]:
bilstm_res = bilstm_model()
bilstm_res

'0.9658172778123058,0.8993341167254211,0.8470301057770545,0.8652037617554859,0.8170594837261504,0.9070071686456729'

In [195]:
def hybrid_model():
    #rfe
    clf = RandomForestClassifier(max_depth=9, n_estimators=200,max_features=10)
    clf_model = clf.fit(x1_0, y1)
    
    testy2pred_prob = clf_model.predict_proba(x2_0_test)
    testy2pred = clf_model.predict(x2_0_test)
    
    testy3pred_prob = clf_model.predict_proba(x3_0_test)
    testy3pred = clf_model.predict(x3_0_test)
    
    testy2_mt = y2.values.reshape(y2.size,1)
    testx20_mt = x2.values
    testy2pred_mt = testy2pred.reshape(testy2pred.size,1)
    
    testy3_mt = y3.values.reshape(y3.size,1)
    testx30_mt = x3.values
    testy3pred_mt = testy3pred.reshape(testy3pred.size,1)
    
    result2_mt = np.concatenate((testx20_mt,testy2pred_prob,testy2pred_mt,testy2_mt),axis = 1)
    result3_mt = np.concatenate((testx30_mt,testy3pred_prob,testy3pred_mt,testy3_mt),axis = 1)
    
    y2_5 = to_categorical(result2_mt[:,19], num_classes=5).reshape(-1,5)
    y3_5 = to_categorical(result3_mt[:,19], num_classes=5).reshape(-1,5)
    
    x2_mt = result2_mt[:, [0,13,14,15,16,17]]
    x3_mt = result3_mt[:, [0,13,14,15,16,17]]
    
#   windows
    look_back = 5
    
    trainX = create_dataset(x2_mt,look_back)
#    trainX = np.array(x2_0)
    trainy = np.array(y2_5)
    testX = create_dataset(x3_mt, look_back)
    testy = np.array(y3_5)
    #testX = np.array(x3_0_test)
    
    train_n1 = int(trainX.shape[0]/look_back)
    test_n1 = int(testX.shape[0]/look_back)
    trainX = trainX.reshape((train_n1, look_back,trainX.shape[1])).astype('float32')
    testX = testX.reshape((test_n1, look_back,testX.shape[1])).astype('float32')
    trainy = trainy.reshape((train_n1, 5)).astype('float32')
    testy = testy.reshape((test_n1, 5)).astype('float32')
    
    model = Sequential()
    model.add(Bidirectional(LSTM(32,input_shape=(trainX.shape[1],trainX.shape[2]))))
    model.add(Dropout(0.4))
    model.add(Dense(5, activation='softmax'))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
    model.fit(trainX, trainy, epochs=50, batch_size=72, verbose=0)
    
    pred = model.predict(testX)
    yhat = np.argmax(pred, axis=1)
    y = np.argmax(testy, axis=1)
    
    report = classification_report(y, yhat, labels=range(5), output_dict=True)
    f1_class = []
    for i in [0,1,2,3,4,'weighted avg']:
        f1 = report[str(i)]['f1-score']
        f1_class.append(f1)
    row_str = ','.join(str(num) for num in f1_class)
    # 保存输出
    output_mt = np.concatenate((testx30_mt,yhat.reshape(yhat.size,1),y.reshape(y.size,1)),axis = 1)
    output_df = pd.DataFrame(output_mt)
    output_df.to_csv('D:/我的文档/手机大数据/数据/识别结果-hybrid-2.csv', index=False, header=False)
    
    return row_str

In [196]:
hybrid_res = hybrid_model()
hybrid_res

'0.9688338493292054,0.948256036795707,0.8775425487754255,0.9088960342979635,0.8606741573033708,0.9323069646050054'

In [76]:
# file = open('D:/我的文档/手机大数据/数据/对比分析100.txt', 'w')
# label = ','.join(['knn_0', 'knn_1','knn_2','knn_3','knn_4','knn_avg','rf_0', 'rf_1','rf_2','rf_3','rf_4','rf_avg',
#                   'xgb_0','xgb_1', 'xgb_2','xgb_3','xgb_4','xgb_avg','lstm_0', 'lstm_1','lstm_2','lstm_3','lstm_4','lstm_avg',
#                  'bilstm_0', 'bilstm_1', 'bilstm_2', 'bilstm_3', 'bilstm_4', 'bilstm_avg',
#                   'hybrid_0','hybrid_1','hybrid_2','hybrid_3','hybrid_4','hybrid_avg'])
# file.write(label + '\n')
# for i in range(100):
# #     kmeans_res = kmeans_model()
#     knn_res = knn_model()
#     rf_res = rf_model()
#     xgb_res = xgb_model()
#     lstm_res = lstm_model()
#     bilstm_res = bilstm_model()
#     hybrid_res = hybrid_model()
#     result = ','.join([knn_res, rf_res, xgb_res, lstm_res, bilstm_res, hybrid_res])
#     print('finish step',i)
#     file.write(result + '\n')
# file.close()

finish step 0
finish step 1
finish step 2
finish step 3
finish step 4
finish step 5
finish step 6
finish step 7
finish step 8
finish step 9
finish step 10
finish step 11
finish step 12
finish step 13
finish step 14
finish step 15
finish step 16
finish step 17
finish step 18
finish step 19
finish step 20
finish step 21
finish step 22
finish step 23
finish step 24
finish step 25
finish step 26
finish step 27
finish step 28
finish step 29
finish step 30
finish step 31
finish step 32
finish step 33
finish step 34
finish step 35
finish step 36
finish step 37
finish step 38
finish step 39
finish step 40
finish step 41
finish step 42
finish step 43
finish step 44
finish step 45
finish step 46
finish step 47
finish step 48
finish step 49
finish step 50
finish step 51
finish step 52
finish step 53
finish step 54
finish step 55
finish step 56
finish step 57
finish step 58
finish step 59
finish step 60
finish step 61
finish step 62
finish step 63
finish step 64
finish step 65
finish step 66
finish step 67
finish step 68
finish step 69
finish step 70
finish step 71
finish step 72
finish step 73
finish step 74
finish step 75
finish step 76
finish step 77
finish step 78
finish step 79
finish step 80
finish step 81
finish step 82
finish step 83
finish step 84
finish step 85
finish step 86
finish step 87
finish step 88
finish step 89
finish step 90
finish step 91
finish step 92
finish step 93
finish step 94
finish step 95
finish step 96
finish step 97
finish step 98
finish step 99